#!/bin/bash
#Echoes some infos about CrashC
#E.G: The number of files which compose the framework, the number of lines of codes, etc...

if [ `basename $PWD` != "crashc" ]; then
	exit 1
fi

echo -e "CrashC 1.0 - Source code statistics\n"
declare -i LINES_NUMBER
declare -i FILES_NUMBER

#Count the number of files in CrashC
FILES_NUMBER=$((`ls ./src/main/c | wc -l` + `ls ./src/main/include | wc -l`))

#Count the number of lines in CrashC
LINES_NUMBER=0
for C_FILE in `ls ./src/main/c`; do
	LINES_NUMBER=$(($LINES_NUMBER + `cat ./src/main/c/$C_FILE | wc -l`))
done

for H_FILE in `ls ./src/main/include`; do
	LINES_NUMBER=$(($LINES_NUMBER + `cat ./src/main/include/$H_FILE | wc -l`))
done

echo "Source files: $FILES_NUMBER"
echo "Total lines: $LINES_NUMBER"
exit 0
